settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: realize
  path: .
  commands: 
    install:
      status: true
      method: go build -o /go/bin/gitxone
    run:
      status: true
      method: /go/bin/gitxone
  watcher:
    extensions:
    - go
    paths:
    - /go/src/
    ignored_paths:
    - .git
    - .config
    - .npm
    - .nuxt
    - .realize
    - node_modules
    - vendor
