version: '3'
services:
  go:
    build: .
    volumes:
      - ./:/go/src/github.com/gitxone/gitxone-core/
    working_dir: /go/src/github.com/gitxone/gitxone-core/
    command: >
      bash -c "dep ensure &&
      realize start --run"
    ports:
      - "10098:10098"
    tty: true
    networks:
      - gitxone-network

  node:
    image: node:latest
    volumes:
      - ./:/home/gitxone/gitxone-core/
    working_dir: /home/gitxone/gitxone-core/
    command: >
      bash -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    networks:
      - gitxone-network

networks:
  gitxone-network:

